Fixes #200 ReadStreamSubscriber does not properly handle errors deliv…
vert-x3/vertx-rx pull request #266
Opened 2021-06-30 12:45 UTC by flukschander

Motivation:

Currently in ReadStreamSubscriber#asReadStream the given Observable/Flowable is directly subscribed to which leads to an IllegalStateException should it only deliver an exception or is empty.
This change will subscribe to the give Observable/Flowable only on a call to ReadStreamSubscriber#handler which also conforms better to the ReadStream specification as it should only start to deliver elements as a handler is set.

2021-06-30 19:41 UTC, vietj commented
we need to have tests for this

2021-06-30 21:32 UTC, flukschander commented
> we need to have tests for this

Sorry for that. Added a few tests

2021-07-28 08:52 UTC, flukschander commented
@vietj did you have time to review yet?

2021-07-28 10:28 UTC, vietj commented
not yet, but it's on my todo list :-)

2021-08-02 08:44 UTC, vietj commented on rx-java-gen/src/main/java/io/vertx/rx/java/ReadStreamSubscriber.java
> +    execOnHandler = s -> {};
this swap should be done within the synchronized block

2021-08-02 08:49 UTC, vietj commented on rx-java3-gen/src/main/java/io/vertx/rxjava3/impl/ReadStreamSubscriber.java
> +    Consumer<Subscriber<R>> action = execOnHandler;
should be done within the synchronized block

2021-08-02 08:50 UTC, vietj commented on rx-java2-gen/src/main/java/io/vertx/reactivex/impl/ReadStreamSubscriber.java
> +    execOnHandler = s -> {};
should be done in the synchronized block

2021-08-02 08:51 UTC, vietj requested changes
minor change with respect to synchronization

2021-08-02 08:53 UTC, flukschander commented
fixed as requested

2021-08-02 13:15 UTC, vietj commented on rx-java-gen/src/main/java/io/vertx/rx/java/ReadStreamSubscriber.java
> +    execOnHandler = s -> {};
here also

2021-08-02 13:15 UTC, vietj commented on rx-java2-gen/src/main/java/io/vertx/reactivex/impl/ReadStreamSubscriber.java
> +    execOnHandler = s -> {};
here also

2021-08-02 13:15 UTC, vietj reviewed
more swap under sync

2021-08-02 14:12 UTC, flukschander commented
done

2021-08-02 17:34 UTC, merged

2021-08-02 17:35 UTC, vietj commented
can you provide a backport PR to 4.1 branch @flukschander ?